spring.application.name=uber-clone
spring.datasource.url=jdbc:postgresql://localhost:5432/uber_clone
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true